export enum ADMIN_ROLE {
  'ADMIN_SUPER' = 'ADMIN_SUPER',
}
export const CONST_ADMIN_ROLE = Object.values(ADMIN_ROLE);

export enum ADMIN_STATUS {
  'APPROVAL' = 'APPROVAL',
  'DELETED' = 'DELETED',
  'DENIED' = 'DENIED',
  'REFUSED' = 'REFUSED',
  'REREQUEST' = 'REREQUEST',
  'WAITING' = 'WAITING',
}
export const CONST_ADMIN_STATUS = Object.values(ADMIN_STATUS);

export enum APPROVED_STATUS {
  'APPROVED' = 'APPROVED',
  'DELETED' = 'DELETED',
  'WAITING' = 'WAITING',
}
export const CONST_APPROVED_STATUS = Object.values(APPROVED_STATUS);

export enum SUBSCRIPTION_STATUS {
  'SUBSCRIBED' = 'SUBSCRIBED',
  'UNSUBSCRIBED' = 'UNSUBSCRIBED',
}
export const CONST_SUBSCRIPTION_STATUS = Object.values(SUBSCRIPTION_STATUS);

export enum NEWSFEED_IS_DISPLAY_STATUS {
  'SHOW' = 'SHOW',
  'HIDE' = 'HIDE',
}
export const CONST_NEWSFEED_IS_DISPLAY_STATUS = Object.values(
  NEWSFEED_IS_DISPLAY_STATUS,
);
export enum USER_ROLE {
  'USER_ROLE_APPROVED' = 'USER_ROLE_APPROVED',
  'USER_ROLE_NOT_APPROVED' = 'USER_ROLE_NOT_APPROVED',
}
export const CONST_STUDENT_ROLE = Object.values(USER_ROLE);
